// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CapMobileWebApp.DAL.Model
{
    public partial class Nominee
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Relation { get; set; }
        public string Aadhar { get; set; }
        public string Pan { get; set; }
        public string Mobile { get; set; }
        public bool? IsMinor { get; set; }
        public string Appointe { get; set; }
        public string Address { get; set; }
        public string Photo { get; set; }
        public long CustomerId { get; set; }

        public virtual Customer Customer { get; set; }
    }
}